#!/bin/bash
mkdir /tmp
mkdir /tmp/Discord_Upgrade
wget -O /tmp/Discord_Upgrade/Discord.deb "https://discord.com/api/download/stable?platform=linux&format=deb"
sudo apt install  /tmp/Discord_Upgrade/Discord.deb 
